@startuml
家厳 -- 宗厳

宗厳 -- 厳勝
宗厳 -- 久斎
宗厳 -- 徳斎
宗厳 -- 五郎右衛門
宗厳 -- 宗矩

厳勝 -- 久三郎
厳勝 -- 利厳
厳勝 -- 権右衛門

利厳 -- 清厳
利厳 -- 利方
利厳 -- 厳包

宗矩 -- 三厳
宗矩 -- 友矩
宗矩 -- 宗冬
宗矩 -- 義仙

宗冬 -- 宗春
宗冬 -- 宗在

class 家厳 << (Y,orchid) >> {
  いえとし
  いえよし
}

class 宗厳 << (Y,orchid) >> {
  むねとし
  むねよし
  --
  但馬守
  石舟斎
}

class 厳勝 << (Y,orchid) >> {
  よしかつ
  としかつ
  --
  尾張柳生の祖
}

class 久斎 << (Y,orchid) >> {

}

class 徳斎 << (Y,orchid) >> {

}

class 五郎右衛門 << (Y,orchid) >> {

}

class 宗矩 << (Y,orchid) >> {
  むねのり
  --
  江戸柳生の祖
  秀忠・家光師範
  柳生藩主
}

class 久三郎 << (Y,orchid) >> {

}

class 利厳 << (Y,orchid) >> {
  としとし
}

class 権右衛門 << (Y,orchid) >> {

}

class 清厳 << (Y,orchid) >> {
  きよとし
}

class 利方 << (Y,orchid) >> {
  としみち
}

class 厳包 << (Y,orchid) >> {
  としかね
}

class 三厳 << (Y,orchid) >> {
  みつよし
  --
  十兵衛
}

class 友矩 << (Y,orchid) >> {
  とものり
}

class 宗冬 << (Y,orchid) >> {
  むねふゆ
}

class 義仙 << (Y,orchid) >> {
  ぎせん
}

class 宗春 << (Y,orchid) >> {
  むねはる
}

class 宗在 << (Y,orchid) >> {
  むねあり
}
@enduml
